<?php

namespace jm\InsurancesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InsuranceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class InsuranceRepository extends EntityRepository
{
}
