<?php

namespace jm\InsurancesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelCategoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RelCategoryRepository extends EntityRepository
{

    public function getCategoryById($categoryId)
    {

        return $this->findOneBy(['id' => $categoryId]);

    }


    public function saveCategory(RelCategory $category)
    {
        //save the Category!

        /* What's really cool is that you'll use these exact two following lines
        whether you're inserting a new Entity or updating an existing one.
        Doctrine figures out the right query to use.*/
        $this->_em->persist($category); //tells Doctrine that you want to save this
        $this->_em->flush(); //But the query isn't made until you call flush()
    }


    /* $criteria is an array e.g. ['name' => $categoryName]
    public function removeCategory(array $criteria)
    {
        $category = $this->$em->getRepository('InsurancesBundle:Category')->findOneBy($criteria);
        if ($category) {
            $this->$em->remove($category);
            $this->$em->flush();
        }
    }*/

    /*
    getCategoriesByParentId(...);
    getCategoryById(...);
    getCategoryByName(...); */
}
