<?php

namespace jm\InsurancesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelInsuranceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RelInsuranceRepository extends EntityRepository
{
    public function getInsuranceById($id)
    {

        return $this->findOneBy(['id' => $id]);

    }


    public function saveIncurance(RelInsurance $insurance)
    {
        //save the Insurance!

        /* What's really cool is that you'll use these exact two following lines
        whether you're inserting a new Entity or updating an existing one.
        Doctrine figures out the right query to use.*/
        $this->_em->persist($insurance); //tells Doctrine that you want to save this
        $this->_em->flush(); //But the query isn't made until you call flush()
    }
}
